### PR TITLE
maybe use azure deployment script?

### PR DESCRIPTION
**Pull request by bewest**
Howdy, these changes add some scripts that azure runs when deploying the project.
The idea was to allow azure to automatically deploy, run `bower install`, and anything else needed when `master` branch changes on github.

Assuming this method works, the web gui for managing azure deploys allows rolling back to any previous version deployed this way.  I added a skeleton azure deploy script generated using the `azure-cli` node package, and then removed most of the `KUDU` stuff which seemed broken.

The result seems to deploy all the assets, and allows fetching data via `/pebble`.
On Azure, the [cgm display appears blank](http://nightscoutba.azurewebsites.net/), with no data, while [my setup with these changes produces very nice results](http://bewest.io:8080/).
pebble-cgm

### CODE REVIEW

**Comment by bewest** [comment]
The picture is with https://github.com/bewest/cgm-pebble running on Brandon's watch.
Might be nice to use a menu/dialog to config the URL at runtime?

**Comment by rnpenguin** [comment]
With your comment about [cgm display appears blank](http://nightscoutba.azurewebsites.net/), I am not sure if this is the same problem but when I was testing pull #20, I noticed that this version had different document properties, bg and timestamp vs sgv and date, I was unable to get the data until I changed it to my mongodb document properties.

**Comment by rnpenguin** [comment]
@ldesboro can you try this out?

**Comment by bewest** [comment]
@rnpenguin this allows azurewebsites to automatically deploy from github.
I've got a couple of azure sites following github's master now using this.

Tested on @brandonarbiter 's nightscout as well as my repair for D.D. and J.S.'s nightscout.  The latter is following my github's master.  It was tested by killing the reverse bug in the last commit in `50dca32` on my local instance of brandon's running on http://bewest.io:8080/pebble (at time of writing), pushing to my master, and watching Dain's watch update correctly without doing anything (because their instance was following my master automatically)!

Also Brandon's checkout started working again (it pulls from his own master, he deploys by editing a PR from my fork into his).

**Pull request merged**
