### PR TITLE
Add alarm silence #7

### PR DESCRIPTION
**Pull request by troggy**
Once alarm is occured, watcher has an option to silence it for certain amount of time. Time spans available: 15 min, 30 min, 60 min, 90 min, 120 min.
Silence applies only to the current alarm type, so if watcher silences regular alarm, urgent alarm (if any) will still be audible. And it's possible to mute urgent alarm too using the same UI.

### CODE REVIEW

**Comment by TC2013** [comment]
Troggy assisted me with setting a windows azure site up to test this and the silencing features worked perfectly.  This is a very nice enhancement.  Thanks troggy!

**Comment by rnpenguin** [comment]
Nice, I will take a look tonight when I do my updates and pull it in.
 Thanks troggy!

On Wed, Mar 19, 2014 at 12:59 PM, TC2013 notifications@github.com wrote:

> Troggy assisted me with setting a windows azure site up to test this and
> the silencing features worked perfectly. This is a very nice enhancement.
> Thanks troggy!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/rnpenguin/cgm-remote-monitor/pull/9#issuecomment-38099521
> .

## 

Ross H. Naylor
Cell (714) 873 -8765

**Comment by rnpenguin** [comment]
I like this idea but have a couple comments/issues:
1. It is not responsive; this is to be viewed on multiple different resolutions (i.e. tables, phones, computers) and when I tried testing on various different resolutions it did not re-position itself nicely.
2. I am not sure if this should be done with 2 buttons.  I like the drop down idea but I feel that I would want to consolidate this into one form of alarm silencer.

The whole point of ACK'ing the alarm is to also broadcast to other watchers that some sort of treatment has been occurred so that they can know not to worry, so maybe the time of the silence should also be sent back to the server (where the time since ACK is also checked) so that duplicate alarms do not occur.

What do you think?

**Comment by TC2013** [comment]
Troggy wrote this piece to my needs, which were overly limiting for others (I'm not a programmer so I didn't think about those larger issues).  But I agree with your assessment, great thinking!

**Comment by troggy** [comment]
Yes, the idea of ACK'ing the alarm makes sense for me. But can you explain me the purpose of silencing the alarm in this case? What scenarios it is required for?
My thought was that "Silence" feature is purely about single watcher, who for whatever reason doesn't want to hear the sound, but still wants to keep an eye on the status (in form "red alarm button with SGV" if alert in place).

**Comment by rnpenguin** [comment]
A use case for this would be that there are 2 caregivers watching a
patient.  When an alarm occurs, whichever caregiver is closest to the
patient will respond and treat the patient, then they would ACK it to
notify the other caregiver that a corrective measure has been issued and
they should not worry.  Now, because treating the issue has a specific lag
time in order for correction to occur, there is silencing of the alarm for
x minutes (right now defaults to 40 minutes).  If x minutes later, the
blood glucose is still in need of correction, then all watchers should be
noticed that a problem exists and correction is still needed, in which case
the closest caregiver can treat, ACK, silence the alarm, and waiting for
correction to occur.  Once the blood glucose has been corrected, then the
silenced alarm should be cleared so that it is not reissued falsely.

On Thu, Mar 20, 2014 at 2:11 AM, Kosta Korenkov notifications@github.comwrote:

> Yes, the idea of ACK'ing the alarm makes sense for me. But can you explain
> me the purpose of silencing the alarm in this case? What scenarios it is
> required for?
> My thought was that "Silence" feature is purely about single watcher, who
> for whatever reason doesn't want to hear the sound, but still wants to keep
> an eye on the status (in form "red alarm button with SGV" if alert in
> place).
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/rnpenguin/cgm-remote-monitor/pull/9#issuecomment-38146823
> .

## 

Ross H. Naylor
Cell (714) 873 -8765

**Comment by troggy** [comment]
Remade to keep silence time on server. Please take a look

**Comment by bewest** [comment]
Just wanted to chime in that this is really cool stuff...

**Comment by rnpenguin** [comment]
Thanks bewest!

**Comment by rnpenguin** [comment]
Hey troggy, I think that your changes were lost in the merge from master.  Please confirm :)

**Comment by troggy** [comment]
You mean upstream/master? No, they weren't. Here they are: https://github.com/rnpenguin/cgm-remote-monitor/pull/9/files

**Comment by rnpenguin** [comment]
UI of the alarm looks great!

Couple of issues/comments:
1.  The regular alarm and urgent alarm are mutually exclusive, but the way you iterate through them creates a scenario where both can co-exists; this is not intended. For example, if the loss function's value is above 0.5, then only urgent alarm should exist and not the regular alarm, same for the reverse.
2.  I am guessing this will change because of 1 above but: 
       for(var alarmType in alarms)
       {
           if(alarms.hasOwnProperty(alarmType))
           {
   does not need the if statement since it is already iterating through its own properties.
3.  This is a current bug, but when the SGV values transition to an appropriate range and loss when an alarm is in progress, the alarm should be cleared. I will setup a separate issue for this one, but thought I might make some visibility of it here.

**Comment by troggy** [comment]
Good point! Fixed

**Pull request merged**
